### ISSUE TITLE
Add option to disable folder arrows

### ISSUE THREAD

**Issue by BeltonMenete** [hello-manoj/Aesthetic-VS-Code-theme#1]
The folder icons in the mano manosh aesthetics theme currently include arrows. To improve customization and reduce visual clutter, please add an option to **disable these arrows**. This feature is already present in popular icon packs like Icons by Mhammed Talhaouy and Material Icon Theme by Philipp Kief.
![Captura de ecrã 2024-08-06 202434](https://github.com/user-attachments/assets/0980fa02-1057-4767-8398-1c02bb32a56e)

**Comment by mnojz** [comment]
Hi @BeltonMenete ,

Thank you for your feedback!

To enhance customization and reduce the size of our extension, we are planning to remove the icon themes from the Aesthetic color theme. Instead, we will focus on providing only the UI color theme and recommend using popular icon themes like Material Icon Theme and Material Product Icon Theme, which already offer the features you're looking for.

This change will make our extension more lightweight and give users the flexibility to choose their preferred icon themes from the marketplace.

We believe this approach will provide a better user experience, but we’d love to hear your thoughts on it.

**Comment by BeltonMenete** [comment]
Thank you for considering my feedback. I appreciate your willingness to explore options for improving the extension.

Separating the UI color theme from the file/folder icons would undoubtedly enhance customization and reduce the extension's size. However, I believe the current file/folder icons are a standout feature that sets your theme apart from others. Their comprehensive coverage of file types and exceptional design are unmatched in other icon packs I've encountered.

I strongly encourage you to consider continuing development of the file/folder icons as a separate package. This would allow users to benefit from both the improved UI color theme and the superior file/folder icons.

By offering these components separately, you would provide maximum flexibility and choice for users.
